### ISSUE TITLE
Re-organize with headings

### ISSUE THREAD

**Issue by buhtz** [szabgab/open-source-by-higher-education#1]
Maybe it is easier for readers if  you would organize your lists geographically via headings. e.g.

```
# North America
## USA
### CA
#### University XYL
- a
- b
### TX
# Asia
## Japan
### Kyoto University
# Europe
## Germany
### Berlin FU
```

Btw: I don't know about any official project supported by a German university. But I'm not in the right position or research area to build a good view onto that topic.

**Comment by szabgab** [comment]
Thanks for the suggestion.

My plan is to convert each entry into a YAML file and then build a web site out of the content where you'll be able to view the list in that way or even filter to what you are interested in.

**Comment by szabgab** [comment]
moved to https://github.com/OSDC-Code-Maven/open-source-by-organizations/issues/4
